platform :ios,'8.0'
target 'GoldRush' do

pod 'Masonry'
pod 'MJExtension'
pod 'AFNetworking'
pod 'SDWebImage'
pod 'MJRefresh'
pod 'SVProgressHUD'
pod 'SDCycleScrollView'
pod 'pop'
pod 'IQKeyboardManager'
pod 'FDFullscreenPopGesture'

pod 'ShareSDK3'
pod 'MOBFoundation'
pod 'ShareSDK3/ShareSDKPlatforms/QQ'

pod 'ShareSDK3/ShareSDKUI'
pod 'ShareSDK3/ShareSDKPlatforms/WeChat'

end
